function [methodinfo,structs,enuminfo,ThunkLibName]=BNSPCIeInterface
%BNSPCIEINTERFACE Create structures to define interfaces found in 'Interface'.

%This function was generated by loadlibrary.m parser version 1.1.6.35 on Sun Jan  8 12:46:20 2012
%perl options:'Interface.i -outfile=BNSPCIeInterface.m -thunkfile=Interface_thunk_pcwin64.c -header=Interface.h'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival,'thunkname', ival);
MfilePath=fileparts(mfilename('fullpath'));
ThunkLibName=fullfile(MfilePath,'Interface_thunk_pcwin64');
% int Constructor ( int RAMWriteEnable , int TrueFrames , char * BoardName ); 
fcns.thunkname{fcnNum}='int32int32int32cstringThunk';fcns.name{fcnNum}='Constructor'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'int32', 'int32', 'cstring'};fcnNum=fcnNum+1;
% void Deconstructor (); 
fcns.thunkname{fcnNum}='voidThunk';fcns.name{fcnNum}='Deconstructor'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
% void SLMPower ( int PowerState ); 
fcns.thunkname{fcnNum}='voidint32Thunk';fcns.name{fcnNum}='SLMPower'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'int32'};fcnNum=fcnNum+1;
% void WriteImage ( int board , unsigned char * Image , unsigned int ImageSize ); 
fcns.thunkname{fcnNum}='voidint32voidPtruint32Thunk';fcns.name{fcnNum}='WriteImage'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'int32', 'uint8Ptr', 'uint32'};fcnNum=fcnNum+1;
% void LoadLUTFile ( int board , char * LUTFile ); 
fcns.thunkname{fcnNum}='voidint32cstringThunk';fcns.name{fcnNum}='LoadLUTFile'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'int32', 'cstring'};fcnNum=fcnNum+1;
methodinfo=fcns;